### ISSUE TITLE
check with bbroeksema to see if might be interested in project

### ISSUE THREAD

**Issue by timelyportfolio** [timelyportfolio/parcoords#1]
@bbroeksema , know you use `R` and also contributed greatly to `parallel-coordinates` so I thought you might be interested in this [`htmlwidget`](http://htmlwidgets.org) designed to provide `parallel-coordinates` in `R`.

**Comment by bbroeksema** [comment]
@timelyportfolio yep I am. I only recently (as in a day or two ago) bumped into this. It's an rChart extension, no?

To give you a bit of background what I've been doing until now: building a web application using opencpu. So, the application is basically an R plugin, though it's not straight forward to get results from the interaction (e.g. filtering, tagging, clustering, etc) back into the R environment.
