### ISSUE TITLE
See / download selected data

### ISSUE THREAD

**Issue by mexindian** [timelyportfolio/parcoords#13]
It would be great to be able to see which exact rows are selected after brushing across several variables. Would there be any way to represent this on the screen, or to at least pass on the items still selected so that they can be downloaded in a dump file?

**Comment by timelyportfolio** [comment]
I am assuming without Shiny.  Is this correct?

**Comment by mexindian** [comment]
Correct. I mean, a data dump is the least... but if a json could be created from the selected components, it could even be passed to https://github.com/renkun-ken/formattable or some such.

**Comment by timelyportfolio** [comment]
Ok, let me try to think through the best way to accomplish this.  Shouldn't
be too difficult.

**Comment by timelyportfolio** [comment]
Adding here in these [lines](https://github.com/timelyportfolio/parcoords/blob/master/inst/htmlwidgets/parcoords.js#L39-L55) probably best place to accomplish this.

**Comment by mexindian** [comment]
I'm sorry, I don't see a change... did you push a modification? Or just asserting that that's probably the best place to intervene? Sorry my JS sucks... :-\

**Comment by timelyportfolio** [comment]
Oh, sorry no change yet.  Just putting there in case somebody can get to it before I do.  I should be able to get at least an example in next couple of days.  Little busier than normal this week.

**Comment by mexindian** [comment]
No worries... I'd help you if I could man. In fact, shall I pull request you some examples so that at least I'm not a scab?

**Comment by timelyportfolio** [comment]
@mexindian here are some temporary solutions:

```
library(parcoords)

# just a basic parcoords with brushing on
pc <- parcoords(mtcars, brushMode = "1d")

# see what it looks like all by itself
pc

# example how to use tasks to get a dump of brushed data
#  in the console
#  note:  this is just a temporary solution
pc$x$tasks <- list(
  htmlwidgets::JS(
'
function(){
  this.parcoords.on("render", function() {
    if(this.brushed()){
      console.log(JSON.stringify(this.brushed()))
    }
  })
}

'
  )
)

pc


# example how to use tasks to get a dump of brushed data
#  in a textarea
#  note:  this is just a temporary solution
pc$x$tasks <- list(
  htmlwidgets::JS(
'
function(){
  this.parcoords.on("render", function() {
    if(this.brushed()){
      document.getElementById("brushdump").innerText = JSON.stringify(this.brushed())
    }
  })
}
'
  )
)

library(htmltools)
browsable(
  tagList(
    pc,
    tags$textarea(id = "brushdump")
  )
)
```
