### ISSUE TITLE
Is it possible to color lines based a field that is not rendered as an axis?

### ISSUE THREAD

**Issue by anobel** [timelyportfolio/parcoords#17]
I'm using `color = list(colorBy = "somefactor"))` to color the lines in the parallel coordinates diagram, but I don't want that factor to be rendered as an axis in the diagram. Is that possible? Ive tried linking to a vector outside the dataframe rendered by `parcoords` without success. This would be quite helpful

**Comment by timelyportfolio** [comment]
Yes, but unfortunately is a hack similar to our last round.  We'll borrow some code from that example.  Let me know how this works.

```
library(parcoords)

parcoords(
  mtcars,
  color = list(
    colorBy = "cyl",
    colorScale = htmlwidgets::JS("d3.scale.category10()")
  ),
  tasks = list(htmlwidgets::JS(
"
function(){
  this.parcoords.hideAxis('cyl')
  this.parcoords.removeAxes();
  this.parcoords.render();
  
  // duplicated from the widget js code
  //  to make sure reorderable and brushes work
  if( this.x.options.reorderable ) {
    this.parcoords.reorderable();
  } else {
    this.parcoords.createAxes();
  }
  
  if( this.x.options.brushMode ) {
  // reset the brush with None
    this.parcoords.brushMode('None')
    this.parcoords.brushMode(this.x.options.brushMode);
    this.parcoords.brushPredicate(this.x.options.brushPredicate);
  }
  
  // delete title from the rownames axis
  d3.select('#' + this.el.id + ' .dimension .axis > text').remove();
}
"    
  ))
)
```

**Comment by anobel** [comment]
excellent! that worked, except that the initial ID axis that we had previously hidden showed up. So I just added the second column to the hideAxis line
`this.parcoords.hideAxis(['names','cyl']);`

**Comment by jtr13** [comment]
This is fantastic! I had the same issue with the initial ID axis. When I added it to the hideAxis line, one of my titles disappeared, so I took out this and it worked:
```
  // delete title from the rownames axis
  d3.select('#' + this.el.id + ' .dimension .axis > text').remove();
```

**Comment by timelyportfolio** [comment]
Fantastic!  I will try to circle back on this one, since I forgot to ever address.

**Comment by timelyportfolio** [comment]
@jtr13, for teaching purposes if you want to demonstrate how to customize any `htmlwidget`, here is the code that will work with `htmlwidgets::onRender`.  For many of my widgets, I added a generally undocumented `tasks` argument before this feature existed.

```
library(parcoords)
library(htmlwidgets)

pc <- parcoords(
  iris,
  color = list(
    colorBy = "Species",
    colorScale = htmlwidgets::JS("d3.scale.category10()")
  ),
  brushMode = "1d",
  reorderable = TRUE,
  rownames = FALSE
)

htmlwidgets::onRender(
  pc,
"
function(el, x){
  var pc = this.instance.parcoords;

  // supply an array of columns to hide
  pc.hideAxis(['names','Species'])
  
  pc.removeAxes();
  pc.render();
  
  // duplicated from the widget js code
  //  to make sure reorderable and brushes work
  if( x.options.reorderable ) {
    pc.reorderable();
  } else {
    pc.createAxes();
  }
  
  if( x.options.brushMode ) {
    // reset the brush with None
    pc.brushMode('None')
    pc.brushMode(x.options.brushMode);
    pc.brushPredicate(x.options.brushPredicate);
  }
  
  // delete title from the rownames axis
  //d3.select('#' + el.id + ' .dimension .axis > text').remove();
}
"    
)
```

**Comment by timelyportfolio** [comment]
@jtr13 one other note, I have added crosstalk support in `feature/crosstalk2` branch.

**Comment by timelyportfolio** [comment]
... and merged `crosstalk` into `master`
