### ISSUE TITLE
README.md nit

### ISSUE THREAD

**Issue by smach** [timelyportfolio/parcoords#2]
Installation needs to be 

devtools::install_github("timelyportfolio/parcoords")

not

devtools::install("timelyportfolio/parcoords")

:-)

Sharon

**Comment by timelyportfolio** [comment]
Thanks so much.  Will fix when I get on computer.  Would love tests, examples, and feedback.

**Comment by timelyportfolio** [comment]
should be fixed.  Thanks again.
