### ISSUE TITLE
possible bug : alpha for controlling opacity not working 

### ISSUE THREAD

**Issue by apratap** [timelyportfolio/parcoords#23]
I dont think latest github version I have is letting me set the opacity for the polylines.  See example below.

-Abhi

![screen shot 2016-05-16 at 9 25 13 am](https://cloud.githubusercontent.com/assets/146127/15295983/223e2a66-1b48-11e6-95e3-bf16e50255ad.png)

**Comment by timelyportfolio** [comment]
Please send some code, so I can work with something. Thanks.
