### ISSUE TITLE
Edit axis titles

### ISSUE THREAD

**Issue by tbadams45** [timelyportfolio/parcoords#26]
In syntagmatic's parallel coordinates library, you can edit axis titles by using the dimensions function.

Is there any way of editing the axis titles in parcoords?

**Comment by timelyportfolio** [comment]
I think this has been implemented in the `feature/crosstalk` branch.  See if https://github.com/timelyportfolio/parcoords/issues/16#issuecomment-169883348 helps.  I'd like to merge the non-crosstalk pieces of this into master soon, so I would welcome some testing.  You can install with

```
devtools::install_github("rstudio/crosstalk")
devtools::install_github("timelyportfolio/parcoords@feature/crosstalk")
```

**Comment by tbadams45** [comment]
I believe you already factored it out - there's no dimensions label in the crosstalk branch, and there's actually a dimensions branch. Should have checked that before asking.

Dimensions branch works great, by the way!

**Comment by tbadams45** [comment]
Figured I wouldn't close in case you wanted to use this as a reminder to merge the dimensions branch. 

Thanks for your help, @timelyportfolio! This is a joy of an htmlwidget to use.

**Comment by tbadams45** [comment]
Is there a way to include a new line in axis titles? With fully descriptive titles (no abbreviations), the titles can overlap.
![capture](https://cloud.githubusercontent.com/assets/8332396/16597627/efe1dab6-42c7-11e6-8ef4-4bb39946b764.PNG)

**Comment by timelyportfolio** [comment]
@tbadams45, as far as I know it is not available unfortunately.  We could use `onRender` to replace with something like [d3plus text](http://d3plus.org/examples/utilities/a39f0c3fc52804ee859a/), but unfortunately text wrapping in svg `text` is painful.

**Comment by timelyportfolio** [comment]
going to close.  Thanks again for the report and question.
