### ISSUE TITLE
Feature request  - set the column labels to be parallel (perpendicular) to the axes instead of horizontal

### ISSUE THREAD

**Issue by talgalili** [timelyportfolio/parcoords#8]
Hello,
I see that when having many coordinates, the labels overlap each other. It would be great to have something like par(las = 2).

Thanks,
Tal

**Comment by timelyportfolio** [comment]
Yes, that  is a great suggestion.  I think I might start with a more indirect approach first, since I realized that I did not include one of my favorite hidden features of my `htmlwidgets`, which are tasks.  Then, I'll think through common tasks that we might be able to wrap in helpful `R` functions.  I should have the first approach complete in just a couple of minutes.

**Comment by timelyportfolio** [comment]
Ok, so I have added another argument `tasks` to the `parcoords` function.  I know it is unfamiliar and not R-like for now, but we can use it to accomplish the rotation like below.

```r
# reinstall parcoords
# devtools::install("timelyportfolio/parcoords")

library(parcoords)

library(parcoords)

parcoords(
  mtcars
  ,# can be a string or htmlwidgets::JS
  tasks = list(
    'function(){
      d3.select(this.el).selectAll(".dimension:nth-child(n+1) > .axis > text")
        //translate assuming down and to right assuming will need more room
        //rotate -90% so vertical
        .attr("transform","translate(10,10) rotate(-90)")
    }'
  )
)
```

I know this is ugly and violates my premise that `htmlwidgets` users shouldn't have to know `HTML/JS/CSS`, so I'll work toward a better solution.

**Comment by talgalili** [comment]
Works great. How would I be able to set it to have the text align left?
(where is the documentation of the relevant syntax?)

**Comment by timelyportfolio** [comment]
If I understand your question correctly, [`text-anchor`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/text-anchor) will be the solution.  Here is the example with this additional change.

```
library(parcoords)

parcoords(
  mtcars
  ,# can be a string or htmlwidgets::JS
  tasks = list(
    'function(){
      d3.select(this.el).selectAll(".dimension:nth-child(n+1) > .axis > text")
        //translate down and to right assuming will need more room
        //     but this might remove our handle for reorderable if brush is on
        //rotate -90 so vertical, but -45 might be better with translate(-5,-5)
        .attr("transform","translate(0,0) rotate(-90)") // changed translate to line up
        .style("text-anchor", "start") //  can be start middle or end
    }'
  )
)
```

**Comment by talgalili** [comment]
Perfect, this solved my issue - thanks!

**Comment by talgalili** [comment]
One more question, when using brushMode = "1d-axes" (or "2D-strums"), I am only able to brush a piece of the observations that are close to one another, but I cannot use "OR" selection.
That is, say I wish to highlight values which are either small OR large - currently I do not see how to do it (only how to choose either the small, or the large, but not to have both selected at the same time).

Is that possible to do?

Thanks,
Tal

**Comment by timelyportfolio** [comment]
That would be a nice feature and has been discussed in a couple issues https://github.com/syntagmatic/parallel-coordinates/issues/69, but `or` brushes are not supported yet.

**Comment by talgalili** [comment]
Bummer,
Thanks anyway :)

**Comment by timelyportfolio** [comment]
@talgalili actually I looked again and this did get implemented.   See this [example](http://syntagmatic.github.io/parallel-coordinates/examples/brushing.html). I will show an `R` example in just a bit.

**Comment by talgalili** [comment]
@timelyportfolio - I see that the option I wanted was 1d-axes-multi
Would it be possible to add it?
(p.s.: your implementation is SUPER useful - thanks!)

**Comment by timelyportfolio** [comment]
Can do but going to be a little messier than I thought.  Think I can get it by tonight.

**Comment by talgalili** [comment]
Wonderful.
p.s.: you didn't write back to me regarding a fix to your blog. I would love to see your blog on r-blogger (i.e.: with a feed that uses png instead of base64 images)

**Comment by timelyportfolio** [comment]
@talgalili thanks so much for the prompting.  The new brush options are really, really nice.

**Comment by talgalili** [comment]
It works like a charm @timelyportfolio , thank you!

May I invite you to a guest post?
(if so, let's continue this via email: tal.galili@gmail.com )

**Comment by talgalili** [comment]
mmm,  I tried "1D-axes-multi", and it didn't seem to work - could you please verify it?

**Comment by timelyportfolio** [comment]
Try `multi` for now.  I'll fix the bug in my `grepl` logic.

**Comment by timelyportfolio** [comment]
Ok, should be fixed now.  Sorry about that.

**Comment by talgalili** [comment]
It now works - thanks again!

**Comment by bbroeksema** [comment]
@timelyportfolio For your info, this seems to be a hack (somewhat) as there currently already label rotation functionality in the d3.parcoords.js.

See: https://github.com/syntagmatic/parallel-coordinates/blob/master/d3.parcoords.js#L604

(and the __.dimensionTitleRotation) property which is accessible trough a getter/setter.

Admittedly, discover ability of this functionality is not that great =:D

**Comment by timelyportfolio** [comment]
@bbroeksema great to know.  I'll try to add it in the `R` htmlwidget.
